### ISSUE TITLE
package info position

### ISSUE THREAD

**Issue by mAmineChniti** [RomanVolkov/go.get.nvim#2]
i think displaying package info at the bottom will be a much better choice, today i tried installing a package using go.get.nvim and i forgot the full package name wish was hidding by the package info display, maybe a better place to put it is the bottom instead of the top, and at the end when i exited and copied the package name i didn't find it, maybe also add an option to paste and get a package that i have the url for but couldn't find in the list, it'd be much better than fully exiting nvim to the terminal and doing it from there

![WindowsTerminal_DAZbi61BTC](https://github.com/user-attachments/assets/8e1c8869-3594-40bf-a39a-8661facdf48d)

**Comment by RomanVolkov** [comment]
@mAmineChniti I thought about moving the preview to the right side, so the list and the preview would have more space 
Just need to take a look how to configure previewer defaults to be at right instead of top

**Comment by RomanVolkov** [comment]
![Screenshot 2024-09-24 at 6 02 31 PM](https://github.com/user-attachments/assets/5e7402c0-ccf5-473b-9510-5b9d4ec1591a)

@mAmineChniti that should be better.
pushed on `main`

**Comment by mAmineChniti** [comment]
tried it, still kinda a bit too tall, i don't think that i need to see like 15-20 package names at once mybe 6-7 would be good and with a bit of a lower position like keep the same distance fom bottom and just change height to be smaller, also do you like my package manual input idea?

**Comment by RomanVolkov** [comment]
@mAmineChniti I think you can configure all of that by yourself since I'm passing `opts` and you can configure Telescope as you want and/or some specific pickers.

> also do you like my package manual input idea

I think that is a good option, I just need to understand how I can access search string from picker's callback.

**Comment by RomanVolkov** [comment]
@mAmineChniti 
https://github.com/RomanVolkov/go.get.nvim/issues/2#issuecomment-2371729631

The screenshot from my 27" screen, it uses your configuration of Telescope, so in your case it should look smaller. But again, you should be able to configure that.

https://github.com/nvim-telescope/telescope.nvim/blob/b324469959908c1c7434eb65d80e87895e6828f7/README.md?plain=1#L471

like this, but to run package search
